name: Test Github Action

on:
  push:
    tags:
      - v*-test*

  workflow_dispatch:

jobs:
  test:
    name: Test Cross-Posting Action

    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: ariskycode/cross-poster@latest
